# Generated by Django 5.1.4 on 2024-12-29 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OneMinBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.DecimalField(decimal_places=10, max_digits=24)),
                ('max_price', models.DecimalField(decimal_places=10, max_digits=24)),
                ('first_price', models.DecimalField(decimal_places=10, max_digits=24)),
                ('last_price', models.DecimalField(decimal_places=10, max_digits=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bar_time', models.DateTimeField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='statistic.symbol')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
